"""empty message

Revision ID: 0b18abe24e7b
Revises:
Create Date: 2025-11-06 09:05:41.434667

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b18abe24e7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.Text(), nullable=False, comment='프로젝트 이름'),
    sa.Column('alias', sa.Text(), nullable=True, comment='프로젝트 별칭, 사용할지는 모르겠습니다'),
    sa.Column('description', sa.Text(), nullable=True, comment='프로젝트 설명, 이것도 사용할지는 모르겠습니다'),
    sa.Column('token', sa.Text(), nullable=True, comment='프로젝트 토큰'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False, comment='사용자 ID'),
    sa.Column('password', sa.String(length=128), nullable=False, comment='사용자 비밀번호, argon2 암호화'),
    sa.Column('permission', sa.Integer(), nullable=False, comment='사용자 권한, 아직 어떻게 쓸지 몰라서 0으로 초기화'),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('username')
    )
    op.create_table('errorlogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='Project ID'),
    sa.Column('errortype', sa.Text(), nullable=True, comment='에러 타입, 예: ValidationError, 근데 일부 라이브러리의 경우 없음'),
    sa.Column('message', sa.Text(), nullable=False, comment='에러 메시지 본문'),
    sa.Column('level', sa.Text(), nullable=False, comment='에러 레벨 (WARNING, ERROR 등)'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Timestamp'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='프로젝트 ID'),
    sa.Column('file_path', sa.Text(), nullable=False, comment='로그 파일 경로'),
    sa.Column('file_name', sa.Text(), nullable=False, comment='로그 파일 이름'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_perms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='프로젝트 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='유저 ID'),
    sa.Column('view', sa.Boolean(), nullable=False, comment='뷰 권한'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.Text(), nullable=False, comment='인증 토큰'),
    sa.Column('user_idx', sa.Integer(), nullable=False, comment='사용자 고유번호'),
    sa.Column('exp', sa.Integer(), nullable=True, comment='토큰 만료 시간(UNIX TIMESTAMP)'),
    sa.ForeignKeyConstraint(['user_idx'], ['users.idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('project_perms')
    op.drop_table('log_files')
    op.drop_table('errorlogs')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
