"""empty message

Revision ID: e8e593517107
Revises: 0b18abe24e7b
Create Date: 2025-11-26 04:15:27.208331

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e8e593517107'
down_revision: Union[str, Sequence[str], None] = '0b18abe24e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_tokens',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=False, comment='FCM 토큰'),
    sa.Column('last_delivery', sa.DateTime(), nullable=True, comment='마지막 푸시 알림 전송 시간'),
    sa.Column('user_idx', sa.Integer(), nullable=False, comment='사용자 고유번호'),
    sa.ForeignKeyConstraint(['user_idx'], ['users.idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('fcm_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fcm_tokens')
    # ### end Alembic commands ###
